FROM plugin-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3.8-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install jupyter==1.1.1
RUN pip install matplotlib==3.7.5
RUN pip install jupyterhub==5.5.0

COPY notebooks/ .

ENTRYPOINT ["jupyter", "notebook", "--ip", "0.0.0.0", "--allow-root"]