FROM plugin-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3.8-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install matplotlib==3.7.5
RUN pip install jupyterlab==4.2.4

ENV HOME=/home/jovyan/work
RUN mkdir -p /home/jovyan/work && chmod -R 777 /home/jovyan/work

COPY notebooks/ .

ENTRYPOINT []
CMD ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]