name: Build/Push Sage Smoke Detection plugin

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - '.github/workflows/docker-publish.yml'
      - 'Dockerfile'
      - 'Dockerfile.notebook'
      - 'notebooks/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/docker-publish.yml'
      - 'Dockerfile'
      - 'Dockerfile.notebook'
      - 'notebooks/**'

jobs:
  build-push-smoke-detection:
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: /ndp/sage/sage-smoke-detection
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set Image Tag
        run: |
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/heads/}"
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          elif [[ "$GITHUB_REF" == refs/pull/* ]]; then
            PR_NUMBER=$(echo "$GITHUB_REF" | cut -d'/' -f3)
            IMAGE_TAG="pr-${PR_NUMBER}"
          fi
          IMAGE_TAG=$(echo "$IMAGE_TAG" | tr '/' '-')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Log in to NRP GitLab Container Registry
        run: echo "${{ secrets.NRP_GITLAB_DEPLOY_TOKEN }}" | docker login ${{ secrets.NRP_GITLAB_REGISTRY_URL }} -u ${{ secrets.NRP_GITLAB_DEPLOY_TOKEN_USERNAME }} --password-stdin

      - name: Build & Push Multi-Arch Smoke Detection Plugin Image
        env:
          REGISTRY_URL: ${{ secrets.NRP_GITLAB_REGISTRY_URL }}
        run: |
          TAGS=(-t "$REGISTRY_URL$IMAGE_PATH:$IMAGE_TAG")
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            TAGS+=(-t "$REGISTRY_URL$IMAGE_PATH:latest")
          fi
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --provenance=false \
            "${TAGS[@]}" \
            --push \
            .
